---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/9/25 7:29 AM
---

---@class AudioEngine Audio engine
local AudioEngine = {}

---@param filename string The audio file to load
---@return number Sound ID
function AudioEngine:LoadSound(filename)
end

---@param id number Sound ID to play
---@param loop boolean Whether or not the sound should loop
---@return boolean Whether playback succeeded
function AudioEngine:PlaySound(id, loop)
end

---@param id number Sound ID to play
function AudioEngine:StopSound(id)
end

function AudioEngine:StopAllSounds()
end

---@param vol number Volume to set, between 0.0 and 1.0
function AudioEngine:SetMasterVolume(vol)
end

---@param id number Sound ID to set the volume for
---@param vol number Volume to set, between 0.0 and 1.0
function AudioEngine:SetSoundVolume(id, vol)
end

---@return boolean Whether audio engine is initialized
function AudioEngine:IsInitialized()
end

---The global audio player instance
---@type AudioEngine Global audio instance
AudioPlayer = {}

return AudioEngine