---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/10/25 7:24 AM
---

---@class SceneState Current scene state
local SceneState = {}

---@param name string Name of the entity
---@return number Entity ID
function SceneState:FindEntityByName(name)
end

---@param entity number Entity ID
---@return Transform Attached transform component
function SceneState:GetEntityTransform(entity)
end

--- Active scene instance
---@type SceneState
Scene = {}

--- Represents an invalid entity ID
---@type number
InvalidEntityID = -1

return SceneState