---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jr.
--- DateTime: 12/2/25 4:43 AM
---

ballSpeed = 500

function onAwake(this)
    print("LuaInterpreter: onAwake() was called")
end

function onUpdate(this, clock)
    local dT = clock:GetDeltaTime()
    local transform = this.transform
    local newPosition = Vec2(0, 0)

    -- Check is one of our movement keys is pressed
    if Input:GetKeyDown(KEY_W) then
        -- Apply a new value to the correct axis scaled by delta time
        newPosition.y = newPosition.y + (ballSpeed * dT)
    end
    if Input:GetKeyDown(KEY_S) then
        newPosition.y = newPosition.y - (ballSpeed * dT)

    end
    if Input:GetKeyDown(KEY_A) then
        newPosition.x = newPosition.x - (ballSpeed * dT)

    end
    if Input:GetKeyDown(KEY_D) then
        newPosition.x = newPosition.x + (ballSpeed * dT)
    end

    -- Translate our entity by the corresponding new amount
    transform:Translate(newPosition)
end

function onDestroyed(this)
    print("LuaInterpreter: onDestroyed() was called")
end